# Generated by Django 4.2.8 on 2026-09-02 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('permission', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('comment', 'Comment'), ('full', 'Full Access')], default='view', max_length=20)),
                ('access_token', models.CharField(max_length=64, unique=True)),
                ('message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedDocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='sharing.documentshare')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_document_access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='sharing.documentshare')),
            ],
            options={
                'db_table': 'share_invitations',
                'indexes': [models.Index(fields=['token'], name='share_invit_token_227d68_idx'), models.Index(fields=['status'], name='share_invit_status_fe931d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['shared_with', 'is_active'], name='document_sh_shared__3b33a9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['access_token'], name='document_sh_access__74808a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['document', 'is_active'], name='document_sh_documen_6177cd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['expires_at'], name='document_sh_expires_a17740_idx'),
        ),
    ]
