# Generated by Django 4.2.8 on 2026-09-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentshare',
            name='download_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='max_opens',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum allowed views; null = unlimited', null=True),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shareddocumentaccesslog',
            name='browser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shareddocumentaccesslog',
            name='device',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shareddocumentaccesslog',
            name='geo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shareddocumentaccesslog',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shareddocumentaccesslog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
