databases:
  - name: secure-vault-db
    databaseName: secure_vault
    user: vault_user
    plan: free
    region: frankfurt

services:
  - type: web
    name: secure-vault-api
    runtime: python
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 60
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_HTTPS
        value: "True"
      - key: USE_SQLITE
        value: "0"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://suredoc-vault.vercel.app,https://secure-document-vault-mostafakamla54-max.vercel.app,http://localhost:3000"
      - key: DATABASE_URL
        fromDatabase:
          name: secure-vault-db
          property: connectionString