# Generated by Django 4.2.8 on 2026-09-02 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('personal', 'Personal'), ('financial', 'Financial'), ('legal', 'Legal'), ('medical', 'Medical'), ('education', 'Education'), ('work', 'Work'), ('other', 'Other')], default='general', max_length=50)),
                ('importance', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('encrypted_file', models.BinaryField(blank=True, null=True)),
                ('key_material', models.BinaryField(blank=True, null=True)),
                ('nonce', models.BinaryField(blank=True, null=True)),
                ('original_extension', models.CharField(blank=True, max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#1976d2', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_tags',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('encrypted_file', models.BinaryField(blank=True, null=True)),
                ('key_material', models.BinaryField(blank=True, null=True)),
                ('nonce', models.BinaryField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('file_size', models.BigIntegerField(default=0)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'db_table': 'document_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['document', 'version_number'], name='document_ve_documen_ff5d1a_idx')],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTagLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='documents.document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='documents.documenttag')),
            ],
            options={
                'db_table': 'document_tag_links',
                'unique_together': {('document', 'tag')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'is_deleted'], name='documents_user_id_c8c388_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'category'], name='documents_user_id_c4f2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'importance'], name='documents_user_id_218dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='documents_created_3c6eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_archived'], name='documents_is_arch_75b4ea_idx'),
        ),
    ]
